[package]
name = "amd_uprof-sys"
version = "0.1.0"
edition = "2024"

[features]
default = []
# generate bindings at build time
bindgen = ["dep:bindgen"]

[build-dependencies]
bindgen = { version = "0.72.0", optional = true }
